#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.5.2ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'bolt.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.5.2ubuntu1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.bolt.conf 0.8-2\~ -- "$@"
# End automatically added section
