#!/bin/sh

set -e

if [ "$1" = install ] && [ ! -f "/etc/crypttab" ]; then
	cat <<-EOC >/etc/crypttab
	# <target name>	<source device>		<key file>	<options>
	EOC
fi

# Automatically added by dh_installdeb/13.6ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init/cryptdisks-udev.conf 2:2.4.0-1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init/cryptdisks.conf 2:2.4.0-1 -- "$@"
# End automatically added section


exit 0
