#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'plymouth-halt.service' 'plymouth-kexec.service' 'plymouth-poweroff.service' 'plymouth-quit-wait.service' 'plymouth-quit.service' 'plymouth-read-write.service' 'plymouth-reboot.service' 'plymouth-start.service' 'plymouth-switch-root-initramfs.service' 'plymouth-switch-root.service' 'systemd-ask-password-plymouth.path' 'systemd-ask-password-plymouth.service' >/dev/null || true
fi
# End automatically added section
