#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.3.3ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'pollinate.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.3.3ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init/pollinate.conf 4.27-0ubuntu1\~ pollinate -- "$@"
# End automatically added section
