#!/bin/sh

set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
	update-alternatives --install /usr/bin/pybabel pybabel /usr/bin/pybabel-python3 200
fi


# Automatically added by dh_python3
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-babel 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-babel  || true
fi

# End automatically added section

