#!/bin/sh
set -e
# Automatically added by dh_installinit/13.2.1ubuntu1
if [ -x "/etc/init.d/secureboot-db" ] && [ "$1" = remove ]; then
	invoke-rc.d secureboot-db stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.2.1ubuntu1
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'secureboot-db.service' >/dev/null || true
fi
# End automatically added section
