#!/bin/sh
# $Id: postinst,v 1.4 2000/08/23 10:08:42 herbert Exp $

set -e

update-alternatives --install /usr/bin/telnet telnet /usr/bin/telnet.netkit 100 \
		    --slave /usr/share/man/man1/telnet.1.gz telnet.1.gz \
				/usr/share/man/man1/telnet.netkit.1.gz

# Automatically added by dh_installmenu/13.6ubuntu1
if [ "$1" = "configure" ] && [ -x "`command -v update-menus`" ]; then
	update-menus
fi
# End automatically added section

