#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'uuidd.service' 'uuidd.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/uuidd" ] ; then
	invoke-rc.d --skip-systemd-native uuidd stop || exit 1
fi
# End automatically added section
